### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by zumbaa101** [kalfasyan/Home_Surveillance_with_Python#1]
Import error:no module named 'flask'

**Comment by kalfasyan** [comment]
Did you install the requirements from the txt file? (`pip install -r requirements.txt`)

**Comment by zumbaa101** [comment]
yes, I'm working on pi. so I installed it from the requirements_pi.txt file.
Ipython gave an error. other than that all were installed. 
Still it gives this error.

**Comment by kalfasyan** [comment]
Flask is in the requirements so it should be installed. Are you running ipython from the same virtual environment? Do `which ipython` and check the output. I suspect you installed ipython with `sudo apt install ipython` and you are running that one instead of the one installed with pip.
