### ISSUE TITLE
ipython errror on raspberry pi

### ISSUE THREAD

**Issue by zumbaa101** [kalfasyan/Home_Surveillance_with_Python#2]
Could not find a version that satisfies the requirement ipython==6.4.0 (from -r requirements_pi.txt (line 7))

**Comment by kalfasyan** [comment]
Try to remove these two lines from the requirements_pi.txt file:
```
ipython==6.4.0
ipython-genutils==0.2.0
```
After the installation, in case you need ipython, just install it independently using pip.
